Feat/binf 495 wgs maf
NCI-GDC/aliquot-maf-tools pull request #38
Opened 2022-08-12 18:49 UTC by tzuni

changes to support WGS MAF work

2022-08-12 18:58 UTC, kmhernan requested changes

2022-08-12 18:58 UTC, kmhernan commented on aliquotmaf/merging/record_merger/impl/v1_0.py
> +            ("caveman", "MNP"),
Did zhenyu etc give you this order? Just want to make sure it was discussed.

2022-08-12 18:58 UTC, kmhernan commented on aliquotmaf/merging/record_merger/impl/v1_0.py
> +            "gatk4_mutect2_pair" "somaticsniper",
did you forget a `,` here?

2022-08-12 19:43 UTC, tzuni commented on aliquotmaf/merging/record_merger/impl/v1_0.py
> +            "gatk4_mutect2_pair" "somaticsniper",
yep, looks like

2022-08-12 19:46 UTC, tzuni commented on aliquotmaf/merging/record_merger/impl/v1_0.py
> +            "gatk4_mutect2_pair" "somaticsniper",
fixed in new commit

2022-08-12 19:50 UTC, kmhernan approved these changes
Approved from my end, but charles may need to see about the failing jenkins.

2022-08-12 19:56 UTC, kmhernan approved these changes

2022-08-15 16:03 UTC, czyszCTDS approved these changes

2022-08-15 16:03 UTC, merged